### ISSUE TITLE
How to make this works on MacOS?

### ISSUE THREAD

**Issue by linonetwo** [biship/RimworldConflictChecker#1]
And is mod def loading in parallism? I have 200+ mod, game loads it needs 10mins, will this tool needs 10mins too?

**Comment by biship** [comment]
It loads the mod def's serially and compares the loaded mod to the previously loaded mods. 
It takes 12s for me and I have 121 mods.

Googling running dot net apps on mac returns this:
https://www.michaelcrump.net/part3-aspnetcore/
There are likely many more posts on how to.
The app is compiled with dot net 4.5.2, so you'll need that version.

Also, there's a chance all the dialogs to find files do not work.
Good luck!
